### ISSUE TITLE
Number of cores used in vignette

### ISSUE THREAD

**Issue by snaketron** [KatjaDanielzik/MetaboDynamics#10]
Great vignette!

Some comments:

- You might not be allowed more than 2 cores in your vignette/examples. Make sure your vignette runs in a reasonable time even if you have to use 1 core.
- Sometimes you use adapt_delta = 0.999 and max_treedepth = 14. These are unusually high values and will make sampling slow. Can you use lower values e.g. adapt_delta = 0.9 and max_treedepth = 11?

**Comment by KatjaDanielzik** [comment]
In examples i have only one metabolite on one core -> examples run very fast (whole check(vignettes=FALSE) in about 5 minutes)

For a faster vignette i might have to change the simulation parameters of the data to be able to run the model with lower values and without errors

**Comment by KatjaDanielzik** [comment]
I set adapt_delta to 0.9 and max_treedepth=10 at 1 core and vignette renders withing 15 minutes on one core
